version: '3'
networks:
  monitoring:
    driver: bridge
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus2
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana2
    ports:
      - 5000:3000
    expose:
      - 5000
    networks:
      - monitoring
  core-app:
    build:
      context: .
      dockerfile: ./apps/core/Dockerfile
      target: development
    command: npm run start:dev core
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - monitoring